<a href="https://colab.research.google.com/github/Mirshodbekkc/Entry/blob/main/Welcome_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#lesson 1
import numpy as np
my_list = list(range(100))
my_list1 = np.array(range(100))
print(my_list) # This is perfectly fine!
print(my_list1)
# An ARRAY (using NumPy) - must hold the same type


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
%time for i in range(100): [x**2 for x in my_list]

CPU times: user 58.6 ms, sys: 2.11 ms, total: 60.7 ms
Wall time: 60.6 ms


In [ ]:
%time for i in range(100): my_list1*2

CPU times: user 68 µs, sys: 1.01 ms, total: 1.08 ms
Wall time: 1.06 ms


# New section

In [ ]:
#lesson 2

lg = [[3,4,3,5,8,9],[8,0,5,5,5,5]]
my = np.array(lg)

In [ ]:
my.ndim #dimension

2

In [ ]:
my.shape  #row, column

(2, 6)

In [ ]:
my.size #all elements

12

In [1]:
import numpy as np

# Create array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Simple slicing
print(arr[2:6])    # [30 40 50 60] - elements from index 2 to 5
print(arr[:4])     # [10 20 30 40] - first 4 elements
print(arr[5:])     # [60 70 80 90 100] - from index 5 to end
print(arr[::2])    # [10 30 50 70 90] - every 2nd element

[30 40 50 60]
[10 20 30 40]
[ 60  70  80  90 100]
[10 30 50 70 90]


In [13]:

arr = np.array([[4,5,3],[1,4,7],[6,4,2]])
arr1 = np.array([[4,5],[8,7],[6,2],[4,6]])    #indexing
arr1


array([[4, 5],
       [8, 7],
       [6, 2],
       [4, 6]])

In [21]:
arr1[2,:]   #slicing

array([6, 2])